default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: local
    hooks:
      - id: Format
        name: Format Code
        entry: poetry run inv swag
        language: system
        pass_filenames: false
        stages: 
          - pre-push
        files: \.(py|ts|tsx)$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: 
          - commit-msg
        args: []

  - repo: local
    hooks:
      - id: pyright
        name: Type Checking
        entry: npx pyright src/orion
        language: node
        types: 
          - python
        stages: 
          - pre-push
        files: \.(py)$
